# Snakemake workflow for calculating coverage profiles around bait/target regions

# Usage:
#source ~/conda_x86
#conda activate snakemake
#snakemake -p --cores --use-conda
#conda deactivate


# Load python packages
import glob
import subprocess


# Specify config file parameters
configfile: "config/config.yaml"
# Define wildcards and variables
run   = config["RUNS"]
baits = config["REGIONS"]["baits"]


# Define target outputs
rule all:
    input:
        expand("data/{run}/{run}_finished.txt",
               run = run),


# Specify rule modules
include: "rules/dx_download.smk"
